export const alreadyVisited = [
    {
        id: 1,
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Hits",
    },
    {
        id: 2,
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Hits",
    },
    {
        id: 3,
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Hits",
    },
    {
        id: 4,
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Hits",
    },
    {
        id: 5,
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "hits",
    },
    {
        id: 6,
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "hits",
    },
]