const productItems = [
    {
        id: "1",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: true,
        new: false,
        discount: false,
        category: "String Art",

    },
    {
        id: "2",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: true,
        discount: false,
        category: "String Art",
    },
    {
        id: "3",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: true,
        category: "String Art",
    },
    {
        id: "4",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "String Art",
    },
    {
        id: "5",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Deco",
    },
    {
        id: "6",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Deco",
    },
    {
        id: "7",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Deco",
    },

    {
        id: "8",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Deco",
    },
    {
        id: "9",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "New",
    },
    {
        id: "10",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "New",
    },
    {
        id: "11",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "New",
    },
    {
        id: "12",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "New",
    },

    {
        id: "14",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "New",
    },

    {
        id: "15",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: true,
        category: "Sale",
    },

    {
        id: "19",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Gifts",
    },
    {
        id: "20",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Gifts",
    },
    {
        id: "21",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Gifts",
    },
    {
        id: "22",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Gifts",
    },
    {
        id: "23",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Hits",
    },
    {
        id: "24",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Hits",
    },
    {
        id: "25",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Hits",
    },
    {
        id: "26",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "Hits",
    },
    {
        id: "27",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "hits",
    },
    {
        id: "28",
        img: "/products/product.png",
        name: "String Art Portrait Kit",
        price: 'USD 19.99',
        hit: false,
        new: false,
        discount: false,
        category: "hits",
    },
];

export default productItems
