export const categories = [
  {
    id: '',
    icon: '',
    title: 'творчі набори',
    description: 'Створи шедевр сьогодні',
    slug: 'tvorchi-nabory',
  },
  {
    id: '',
    icon: '',
    title: 'декор',
    description: 'Краса в деталях',
    slug: 'decor',
  },
  {
    id: '',
    icon: '',
    title: 'подарунки',
    description: 'Даруйте натхнення',
    slug: 'podarunky',
  },
  {
    id: '',
    icon: '',
    title: 'новинки',
    description: 'Нове у нашому магазині',
    slug: 'novynky',
  },
  {
    id: '',
    icon: '',
    title: 'знижки',
    description: 'Вигідні пропозиціі',
    slug: 'znyzhky',
  },
  {
    id: '',
    icon: '',
    title: 'художні товари',
    description: 'Створюйте Надихайтесь',
    slug: 'hudozhni-tovary',
  },
  {
    id: '',
    icon: '',
    title: 'аксесуари',
    description: 'Незамінні дрібниці',
    slug: 'aksesuary',
  },
  {
    id: '',
    icon: '',
    title: 'хобі та розваги',
    description: 'Творчість і розваги в одному місці',
    slug: 'hobbi-ta-rozvagy',
  },
  {
    id: '',
    icon: '',
    title: 'Косметичні засоби',
    description: 'Краса, що дарує впевненість',
    slug: 'kosmetychni-zasoby',
  },
  {
    id: '',
    icon: '',
    title: 'канцелярія',
    description: 'Зручність і порядок',
    slug: 'kancelyarija',
  },
];
